version: "3.2"

services:
  dev:
    container_name: brock
    image: paritytech/ci-linux:production
    working_dir: /var/www/brock
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/brock/.cargo
    volumes:
      - .:/var/www/brock
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/brock --dev --ws-external"
